# Data Preprocessing

This notebook contains the data preprocessing part of the project.

Contents:
1. [Imporiting Libraries](#Importing)
2. [Loading Data](#Loading-data)
3. [Cleaning Data](#cleaning-data)
4. [Statistical Summary](#statistical-summary)
5. [Saving Dataframe](#saving-the-dataframe)

# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading data
Loading the data into a dataframe.

In [2]:
df = pd.read_csv('../data/GlobalWeatherRepository.csv')

In [3]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

# Cleaning Data
- Handling Missing Values
- Converting to appropriate data types
- Checking duplicates

In [4]:
df.isna().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

The dataset has no null values.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30096 entries, 0 to 30095
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       30096 non-null  object
 1   location_name                 30096 non-null  object
 2   latitude                      30096 non-null  float64
 3   longitude                     30096 non-null  float64
 4   timezone                      30096 non-null  object
 5   last_updated_epoch            30096 non-null  int64
 6   last_updated                  30096 non-null  object
 7   temperature_celsius           30096 non-null  float64
 8   temperature_fahrenheit        30096 non-null  float64
 9   condition_text                30096 non-null  object
 10  wind_mph                      30096 non-null  float64
 11  wind_kph                      30096 non-null  float64
 12  wind_degree                   30096 non-null  int64
 13  wind_direction                30096 non-null  object
 14  pressure_mb                   30096 non-null  float64
 15  pressure_in                   30096 non-null  float64
 16  precip_mm                     30096 non-null  float64
 17  precip_in                     30096 non-null  float64
 18  humidity                      30096 non-null  int64
 19  cloud                         30096 non-null  int64
 20  feels_like_celsius            30096 non-null  float64
 21  feels_like_fahrenheit         30096 non-null  float64
 22  visibility_km                 30096 non-null  float64
 23  visibility_miles              30096 non-null  float64
 24  uv_index                      30096 non-null  float64
 25  gust_mph                      30096 non-null  float64
 26  gust_kph                      30096 non-null  float64
 27  air_quality_Carbon_Monoxide   30096 non-null  float64
 28  air_quality_Ozone             30096 non-null  float64
 29  air_quality_Nitrogen_dioxide  30096 non-null  float64
 30  air_quality_Sulphur_dioxide   30096 non-null  float64
 31  air_quality_PM2.5             30096 non-null  float64
 32  air_quality_PM10              30096 non-null  float64
 33  air_quality_us-epa-index      30096 non-null  int64
 34  air_quality_gb-defra-index    30096 non-null  int64
 35  sunrise                       30096 non-null  object
 36  sunset                        30096 non-null  object
 37  moonrise                      30096 non-null  object
 38  moonset                       30096 non-null  object
 39  moon_phase                    30096 non-null  object
 40  moon_illumination             30096 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 9.4+ MB

The datatypes of the columns are correct.

In [6]:
df.duplicated().sum()

0

There are no duplicated in the dataset

# Statistical Summary

In [7]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,30096.000000,30096.000000,3.009600e+04,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,...,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000,30096.000000
mean,19.132083,21.969201,1.722537e+09,25.743129,78.339228,8.560663,13.781134,176.260832,1012.425306,29.896218,...,20.292344,460.003296,64.979336,10.053476,7.282977,17.877346,33.602397,1.438796,1.969631,49.496312
std,24.485795,65.853435,3.938018e+06,7.174114,12.913489,11.830692,19.039875,100.303245,6.209667,0.183018,...,20.379515,1070.886244,42.729820,22.527067,60.349860,48.422078,76.903990,0.819501,1.989057,34.998246
min,-41.300000,-175.200000,1.715849e+09,-8.400000,16.900000,2.200000,3.600000,1.000000,976.000000,28.820000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.500000,0.500000,1.000000,1.000000,0.000000
25%,3.750000,-6.840000,1.719064e+09,22.100000,71.800000,4.300000,6.800000,92.000000,1009.000000,29.800000,...,11.500000,203.600000,34.300000,0.600000,0.500000,2.800000,5.100000,1.000000,1.000000,15.000000
50%,17.250000,23.320000,1.722602e+09,26.600000,79.900000,7.600000,12.200000,172.000000,1013.000000,29.910000,...,18.400000,262.700000,60.000000,2.035000,1.500000,7.900000,13.320000,1.000000,1.000000,50.000000
75%,40.400000,49.882200,1.725971e+09,30.000000,86.000000,11.900000,19.100000,260.000000,1016.000000,30.000000,...,26.300000,397.750000,90.000000,7.700000,5.365000,18.315000,32.381250,2.000000,2.000000,83.000000
max,64.150000,179.220000,1.729245e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,1045.000000,30.860000,...,2970.400000,38879.398000,480.700000,427.700000,255.855000,1614.100000,1814.400000,6.000000,10.000000,100.000000

In [8]:
# summary for key features like temperature, humidity, wind speed, precipitation

cols = []
for col in df.columns:
    if (
        col.startswith('temp') or
        col.startswith('wind') or
        col.startswith('humidity') or
        col.startswith('preci')
    ) and df[col].dtype != 'O':
        cols.append(col)

print(f"Key Columns: \n{cols}")

Key Columns:
['temperature_celsius', 'temperature_fahrenheit', 'wind_mph', 'wind_kph', 'wind_degree', 'precip_mm', 'precip_in', 'humidity']

In [9]:
for col in cols:
    print(f'{col}: ')
    print(f"Min: {df[col].min()}")
    print(f"Max: {df[col].max()}")
    
    print('-----------')
    print()

temperature_celsius:
Min: -8.4
Max: 49.2
-----------

temperature_fahrenheit:
Min: 16.9
Max: 120.6
-----------

wind_mph:
Min: 2.2
Max: 1841.2
-----------

wind_kph:
Min: 3.6
Max: 2963.2
-----------

wind_degree:
Min: 1
Max: 360
-----------

precip_mm:
Min: 0.0
Max: 27.82
-----------

precip_in:
Min: 0.0
Max: 1.1
-----------

humidity:
Min: 2
Max: 100
-----------

# Saving the Dataframe

In [10]:
df.to_csv('../data/CleanedGlobalWeatherRepository.csv', index=False)